# PageCMS Configuration for adeos-design.com
# Configuration adjusted to match the actual Eleventy project structure

media:
  input: src/images
  output: /images

content:
  # Home section pages (aktzeichnen, art, projects)
  - name: home_sections
    label: Home Sections
    type: collection
    path: src/home_sections/
    # filename: index.md
    format: yaml-frontmatter
    view:
      fields: [title, eleventyNavigation.order]
      primary: title
      sort: [eleventyNavigation.order]
    fields:
      - name: title
        label: Section Title
        type: string
        required: true
      - name: subtitle
        label: Section Subtitle
        type: string
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - name: key
            label: Navigation Key
            type: string
          - name: order
            label: Order
            type: number
      - name: img
        label: Featured Image
        type: string
        description: Image filename from src/images/
      - name: teaser
        label: Teaser Text
        type: text

  # Home page (index.njk)
  # - name: home
  #   label: Home Page
  #   type: file
  #   path: src/index.njk
  #   format: yaml-frontmatter
  #   fields:
  #     - name: title
  #       label: Page Title
  #       type: string
  #       required: true

  # Legal pages
  - name: legals
    label: Legal Pages
    type: file
    path: src/legals.md
    format: markdown
    fields:
      - name: body
        label: Content
        type: text  # rich-text
        required: true

  # Site settings (src/_data/site.json)
  - name: site
    label: Site settings
    path: src/_data/site.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: subtitle
        label: Website subtitle
        type: string
      - name: fqdn
        label: Website Domain
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: baseUrl
        label: GitHub Pages Base URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: instagram
        label: Instagram Link
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: image
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)

settings:
  content:
    merge: true
